source "https://rubygems.org"

gem "analog", "~> 0.3"
gem "em-websocket", "~> 0.5", ">= 0.5.1"
gem "eventmachine", "~> 1.0", ">= 1.0.4"
gem "midi-eye", "~> 0.3", ">= 0.3.7"
gem "osc-ruby", "~> 1.1", ">= 1.1.1"
gem "rack"
gem "rainbow", "~> 2.0", ">= 2.0.0"
